name: TrackYourStop
description: Track your favorite mvv stops.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # iOS style icons.
  cupertino_icons: ^1.0.2
  # Logging
  logger: ^1.1.0
  # Date formatting
  intl: ^0.18.0
  # State management
  hooks_riverpod: ^2.1.1
  # Routing
  auto_route: ^5.0.3
  # Database storage
  sqflite: ^2.2.2
  # Toasts
  fluttertoast: ^8.1.2
  english_words: ^4.0.0
  http: ^0.13.5
  flutter_typeahead: ^4.1.1
  settings_ui: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Linter
  flutter_lints: ^2.0.0
  # Generate route files
  build_runner: ^2.3.2
  http_parser: ^4.0.0
  grpc: ^3.1.0
  auto_route_generator: ^5.0.3
  flutter_launcher_icons: ^0.11.0
  flutter_svg: ^1.1.6
  flutter_image_stack: ^0.0.6

# The following section is specific to Flutter packages.
flutter:
  # Enable material design
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png