# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

run-name: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches: ["master", "feature/*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Get flutter packages
        run: flutter pub get
      - name: Generate localization
        run: flutter gen-l10n
      - name: Analyze project source
        run: dart analyze
      - name: Run tests
        run: flutter test
